package Entities;
// Generated 29-nov-2016 15:59:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer idCategory;
     private String description;
     private Set transactionses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(String description) {
        this.description = description;
    }
    public Categories(String description, Set transactionses) {
       this.description = description;
       this.transactionses = transactionses;
    }
   
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }




}


