package Entities;
// Generated 29-nov-2016 15:59:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private Integer idTransaction;
     private Categories categories;
     private Types types;
     private Users users;
     private String description;
     private BigDecimal value;
     private Date date;

    public Transactions() {
    }

    public Transactions(Categories categories, Types types, Users users, String description, BigDecimal value, Date date) {
       this.categories = categories;
       this.types = types;
       this.users = users;
       this.description = description;
       this.value = value;
       this.date = date;
    }
   
    public Integer getIdTransaction() {
        return this.idTransaction;
    }
    
    public void setIdTransaction(Integer idTransaction) {
        this.idTransaction = idTransaction;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Types getTypes() {
        return this.types;
    }
    
    public void setTypes(Types types) {
        this.types = types;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


