package Entities;
// Generated 28-nov-2016 16:56:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Types generated by hbm2java
 */
public class Types  implements java.io.Serializable {


     private Integer idType;
     private String description;
     private Set transactionses = new HashSet(0);

    public Types() {
    }

    public Types(String description, Set transactionses) {
       this.description = description;
       this.transactionses = transactionses;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }




}


